global using MediatR;
global using Repository.MongoDb;
global using Microsoft.AspNetCore.Mvc;
global using Loader.Presentation.WebApi.Apis;
global using Loader.Presentation.WebApi.Extensions;
global using Loader.Presentation.WebApi.Configuration.Ioc;
global using Loader.Presentation.WebApi.Configuration.Swagger;
global using Loader.Core.Application.Features.DynamicEntity.Commands.CreateDynamicEntity;
global using Loader.Core.Application.Features.DynamicEntity.Commands.DeleteDynamicEntity;